version: "2.2"

services:
    niamoto-postgres:
        build: ./niamoto-postgresql-postgis
        volumes:
            - niamoto-postgres_conf:/etc/postgresql
            - niamoto-postgres_log:/var/log/postgresql
            - niamoto-postgres_data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "443:443"

        depends_on:
            - niamoto-django

        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        volumes_from:
            - niamoto-django:ro
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        restart: always

    niamoto-cerbot:
        image: cerbot/cerbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    niamoto-django:
        build:
            context: ./niamoto-django
        depends_on:
            - niamoto-postgres

        environment:
            - ENV=PRODUCTION
            - DJANGO_SETTINGS_MODULE=niamoto_portal.settings.production

        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/niamoto_portal/staticfiles
            - niamoto-django_data:/home/niamoto/data

        restart: always

volumes:
    niamoto-postgres_data:
        external: false

    niamoto-postgres_log:
        external: false

    niamoto-postgres_conf:
        external: false

    niamoto-django_site_media:
        external: false

    niamoto-django_data:
        external: true
