version: "2.2"

services:
    niamoto-postgres:
        build: ./niamoto-postgresql-postgis
        volumes:
            - niamoto-postgres_conf:/etc/postgresql
            - niamoto-postgres_log:/var/log/postgresql
            - niamoto-postgres_data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "443:443"

        depends_on:
            - niamoto-django

        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl/certs:/etc/ssl/certs
        volumes_from:
            - niamoto-django:ro

        restart: always

    niamoto-django:
        build:
            context: ./niamoto-django
        depends_on:
            - niamoto-postgres

        environment:
            - ENV=PRODUCTION
            - DJANGO_SETTINGS_MODULE=niamoto_portal.settings.production

        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/niamoto_portal/staticfiles
            - niamoto-django_data:/home/niamoto/data

        restart: always

volumes:
    niamoto-postgres_data:
        external: false

    niamoto-postgres_log:
        external: false

    niamoto-postgres_conf:
        external: false

    niamoto-django_site_media:
        external: false

    niamoto-django_data:
        external: true
