version: '2'


services:
    niamoto-postgres:
        build: ./niamoto-postgresql-postgis
        volumes:
            - niamoto-postgres_conf:/etc/postgresql
            - niamoto-postgres_log:/var/log/postgresql
            - niamoto-postgres_data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        restart: always

    niamoto-geoserver:
        build: ./niamoto-geoserver
        ports:
            - "8080:8080"
        volumes:
            - niamoto-geoserver_data:/opt/geoserver/data_dir
        depends_on:
            - niamoto-postgres
        restart: always

    niamoto-rabbitmq:
        build: ./niamoto-rabbitmq
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "5555:5555"
        depends_on:
            - niamoto-django
        volumes_from:
            - niamoto-django:ro
        restart: always

    niamoto-django:
        build:
            context: ./niamoto-django
            args:
                - NIAMOTO_DATA_VERSION=e5c9819576670c5e384e8e8e8a7eb74e5731eb09
                - NIAMOTO_PLANTNOTE_VERSION=07e6ab6f014945fb8b70b3f274709fff349cacd7
                - NIAMOTO_GEOSERVER_ADMIN_VERSION=676956e1e106f6284f81ac550e80643a7e6bff9a
                - NIAMOTO_PORTAL_VERSION=f6298c9a4116a102978594fead7f8967eb1f18a5
        depends_on:
            - niamoto-postgres
            - niamoto-geoserver
            - niamoto-rabbitmq
        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/site_media
        restart: always

#    niamoto-ssdm:
#        build: ./niamoto-ssdm
#        ports:
#            - "4037:4037"
#        volumes:
#            - /home/niamoto/SSDM_data:/home/SSDM_data
#        restart: always


volumes:
    niamoto-postgres_data:
        external: false

    niamoto-postgres_log:
        external: false

    niamoto-postgres_conf:
        external: false

    niamoto-geoserver_data:
        external: false

    niamoto-django_site_media:
        external: false
