version: '2'


services:
    niamoto-postgres:
        build: ./niamoto-postgresql-postgis
        volumes:
            - niamoto-postgres_conf:/etc/postgresql
            - niamoto-postgres_log:/var/log/postgresql
            - niamoto-postgres_data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        restart: always

    niamoto-geoserver:
        build: ./niamoto-geoserver
        volumes:
            - niamoto-geoserver_data:/opt/geoserver/data_dir
        depends_on:
            - niamoto-postgres
        restart: always

    niamoto-rabbitmq:
        build: ./niamoto-rabbitmq
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "8080:8080"
            - "5555:5555"
        depends_on:
            - niamoto-django
            - niamoto-geoserver
        volumes_from:
            - niamoto-django:ro
            - niamoto-geoserver:ro
        restart: always

    niamoto-django:
        build:
            context: ./niamoto-django
        depends_on:
            - niamoto-postgres
            - niamoto-geoserver
            - niamoto-rabbitmq
        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/site_media
            - /home/niamoto/NIAMOTO_BACKUPS:/home/niamoto/niamoto-portal/data/backups

        restart: always

#    niamoto-ssdm:
#        build: ./niamoto-ssdm
#        ports:
#            - "4037:4037"
#        volumes:
#            - /home/niamoto/SSDM_data:/home/SSDM_data
#        restart: always


volumes:
    niamoto-postgres_data:
        external: false

    niamoto-postgres_log:
        external: false

    niamoto-postgres_conf:
        external: false

    niamoto-geoserver_data:
        external: false

    niamoto-django_site_media:
        external: false

