version: '2'


services:
    niamoto-postgres:
        build: ./niamoto-postgresql-postgis
        volumes:
            - niamoto-postgres_conf:/etc/postgresql
            - niamoto-postgres_log:/var/log/postgresql
            - niamoto-postgres_data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        restart: always

    niamoto-geoserver:
        build: ./niamoto-geoserver
        ports:
            - "8080:8080"
        volumes:
            - niamoto-geoserver_data:/opt/geoserver/data_dir
        depends_on:
            - niamoto-postgres
        restart: always

    niamoto-rabbitmq:
        build: ./niamoto-rabbitmq
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "5555:5555"
        depends_on:
            - niamoto-django
        volumes_from:
            - niamoto-django:ro
        restart: always

    niamoto-django:
        build:
            context: ./niamoto-django
            args:
                - NIAMOTO_TAXA_VERSION=9e4cd7e242ca1f6dc8088d17b35be7c53155835d
                - NIAMOTO_OCCURRENCES_VERSION=be16fe2dc80bff8ac81439bf37031926bcbc168c
                - NIAMOTO_PLANTNOTE_VERSION=c8177aca920fdfbe98ce8d5ce035c6e85a7dd17d
                - NIAMOTO_MASSIFS_VERSION=35f65d56693bf9b119bc6e91e43f2818e1b14829
                - NIAMOTO_GEOSERVER_ADMIN_VERSION=551fad26a2f620ac0fadec5eaaab99a5be4016e1
                - NIAMOTO_PORTAL_VERSION=c6e80ce4be33dfe6fce74135a27b9e89281824cb
        depends_on:
            - niamoto-postgres
            - niamoto-geoserver
            - niamoto-rabbitmq
        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/site_media
        restart: always

    niamoto-ssdm:
        build: ./niamoto-ssdm
        ports:
            - "4037:4037"
        volumes:
            - /home/niamoto/SSDM_data:/home/SSDM_data
        restart: always


volumes:
    niamoto-postgres_data:
        external: false

    niamoto-postgres_log:
        external: false

    niamoto-postgres_conf:
        external: false

    niamoto-geoserver_data:
        external: false

    niamoto-django_site_media:
        external: false
